var clean       = require('gulp-clean');
var concat      = require('gulp-concat');
var gulp        = require('gulp');
var htmlMin     = require('gulp-htmlmin');
var prefixer    = require('gulp-autoprefixer');
var sass        = require('gulp-sass');
var runSequence = require('run-sequence');
var uglify      = require('gulp-uglify');

/**
 * Limpa diretórios de produção
 */
gulp.task('clean', function() {
	return gulp.src(['./public/assets/', './storage/smarty/templates'])
	.pipe(clean());
});

/**
 * Minifica e concatena arquivos Javascript
 */
gulp.task('jsMin', function() {
	return gulp.src([
		'./bower_components/jquery/dist/jquery.js',
		'./bower_components/jquery.maskedinput/dist/jquery.maskedinput.js',
		'./resources/assets/js/*.js'
	])
	.pipe(uglify())
	.pipe(concat('app.js'))
	.pipe(gulp.dest('./public/assets/js/'));
});

/**
 * Minifica os templates HTML
 */
gulp.task('htmlMin', function() {
	return gulp.src('./resources/views/templates/**/*.tpl')
	.pipe(htmlMin({
		collapseWhitespace: true,
		includeAutoGeneratedTags: false,
		removeComments: true
	}))
	.pipe(gulp.dest('./storage/smarty/templates'));
});

/**
 * Compila os arquivos SASS
 */
gulp.task('cssMin', function () {
	return gulp.src('./resources/assets/scss/*.scss')
	.pipe(sass({
		outputStyle: 'compressed'
	}))
	.pipe(prefixer({
		versions: ['last 2 browsers']
	}))
	.pipe(gulp.dest('./public/assets/css'));
});


//------------------------------------------------------------
// Watches
//------------------------------------------------------------

/**
 * SASS Watch
 */
gulp.task('watchCss', function() {
	return gulp.watch('./resources/assets/scss/**/*.scss', ['cssMin']);
});

/**
 * JS Watch
 */
gulp.task('watchJs', function() {
	return gulp.watch('./resources/assets/js/*.js', ['jsMin']);
});

/**
 * HTML Watch
 */
gulp.task('watchHtml', function() {
	return gulp.watch('./resources/views/templates/**/*.tpl', ['htmlMin']);
});


//------------------------------------------------------------
// Multi tasks
//------------------------------------------------------------

/**
 * Roda todas as tasks principais
 */
gulp.task('default', function(callback) {
	return runSequence('clean', ['cssMin', 'jsMin', 'htmlMin'], callback);
});

/**
 * Watch tasks
 */
gulp.task('watch', function(callback) {
	return runSequence('watchCss', 'watchJs', 'watchHtml', callback);
});
